# This is a basic workflow to help you get started with Actions

name: Deploy PROD Widget

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - '**@notifire/widget**'
      - '**@notifire/shared**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test_widget:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 80

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup kernel for react native, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - uses: actions/setup-node@v2
        with:
          node-version: '15.11.0'
      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2.8

      - name: restore lerna
        uses: actions/cache@master
        with:
          path: |
            node_modules
            **/node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      # Runs a single command using the runners shell
      - name: Install project dependencies
        run: yarn install

      # Runs a single command using the runners shell
      - name: Bootstrap
        run: yarn run bootstrap

      # Runs a single command using the runners shell
      - name: Build
        run: CI='' yarn run build:widget

      # Runs a single command using the runners shell
      - name: Start Client
        run: yarn run start:widget &

      # Runs a single command using the runners shell
      - name: Start WS
        run: yarn run start:ws &

      # Runs a single command using the runners shell
      - name: Wait for WS
        run: npx wait-on --timeout=30000 http://localhost:1340/v1/health-check

      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          NODE_ENV: test
          CYPRESS_RECORD_KEY: 8d46726d-57b2-48da-9aca-19bad108964c
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working-directory: apps/widget
          start: yarn run start:api
          wait-on: http://localhost:3500/v1/health-check
          record: true
          browser: chrome
          headless: true
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v2.2

      - name: Build PROD
        env:
          REACT_APP_API_URL: https://api.notifire.co
          REACT_APP_SENTRY_DSN: https://d3074835f0b443d4831b3abcf1638fdb@o568359.ingest.sentry.io/5739010
          REACT_APP_WS_URL: https://ws.notifire.co
          REACT_APP_ENVIRONMENT: prod
        working-directory: apps/widget
        run: npm run build

      - name: Deploy WIDGET to PROD
        uses: scopsy/actions-netlify@develop
        with:
          publish-dir: apps/widget/build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: prod
          production-deploy: true
          alias: prod
          github-deployment-environment: production
          github-deployment-description: Web Deployment
          netlify-config-path: apps/widget/netlify.toml
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: 230e24e9-cc5f-45e7-af1d-403560404229
        timeout-minutes: 1
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: apps/widget
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: notifire
          SENTRY_PROJECT: widget
        with:
          environment: prod
          version: v${{ steps.package-version.outputs.current-version }}
          sourcemaps: apps/widget/build
