# This is a basic workflow to help you get started with Actions

name: Deploy PROD SDK


# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - '**@notifire/sdk@**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy_sdk:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 80

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup kernel for react native, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - uses: actions/setup-node@v2
        with:
          node-version: '15.11.0'

      - name: restore lerna
        uses: actions/cache@master
        with:
          path: |
            node_modules
            **/node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      # Runs a single command using the runners shell
      - name: Install project dependencies
        run: yarn install

      # Runs a single command using the runners shell
      - name: Bootstrap
        run: yarn run bootstrap

      # Runs a single command using the runners shell
      - name: Build
        working-directory: libs/sdk
        run: CI='' yarn run build:prod

      - name: Deploy SDK to PROD
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: libs/sdk/dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: prod
          production-deploy: true
          alias: prod
          github-deployment-environment: production
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: 89515612-8559-4b1d-9050-293ca85177d5
        timeout-minutes: 1


