# This is a basic workflow to help you get started with Actions

name: Deploy PROD WEB

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - '**@notifire/web**'
      - '**@notifire/shared**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test_web:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 80

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup kernel for react native, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - uses: actions/setup-node@v2
        with:
          node-version: '15.11.0'
      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2.8

      - name: restore lerna
        uses: actions/cache@master
        with:
          path: |
            node_modules
            **/node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}


      # Runs a single command using the runners shell
      - name: Install project dependencies
        run: yarn install

      # Runs a single command using the runners shell
      - name: Bootstrap
        run: yarn run bootstrap

      - name: Start Local Stack
        env:
          DEFAULT_REGION: us-east-1
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCOUNT_ID: "000000000000"
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_EC2_METADATA_DISABLED: true
        working-directory: environment/test
        run: |
          docker-compose up -d
          sleep 5
          max_retry=30
          counter=0
          until $command
          do
             sleep 1
             [[ counter -eq $max_retry ]] && echo "Failed!" && exit 1
             aws --endpoint-url=http://localhost:4566 s3 ls
             echo "Trying again. Try #$counter"
             ((counter++))
          done
          aws --endpoint-url=http://localhost:4566 s3 mb s3://notifire-test

      # Runs a single command using the runners shell
      - name: Build
        run: CI='' yarn run build:web

      # Runs a single command using the runners shell
      - name: Start Client
        run: yarn run start:web &

      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          NODE_ENV: test
          CYPRESS_RECORD_KEY: 6ffb0ad1-35b2-4916-b097-5e28f488f0e3
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          record: true
          working-directory: apps/web
          start: yarn run start:api
          wait-on: http://localhost:1336/v1/health-check
          browser: chrome
          headless: true

      - name: Build
        env:
          REACT_APP_API_URL: https://api.notifire.co
          REACT_APP_WIDGET_SDK_PATH: https://sdk.notifire.co/sdk.umd.min.js
          REACT_APP_SENTRY_DSN: https://e19f8fa6743e49cab28aadbe3b04f197@o568359.ingest.sentry.io/5738524
          REACT_APP_ENVIRONMENT: prod
          REACT_APP_NOTIFIRE_APP_ID: r-kSpel8zWeZ
        working-directory: apps/web
        run: npm run build

      - name: Deploy WEB to PROD
        uses: scopsy/actions-netlify@develop
        with:
          publish-dir: apps/web/build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: Prod deployment
          production-deploy: true
          alias: prod
          github-deployment-environment: production
          github-deployment-description: Web Deployment
          netlify-config-path: apps/web/netlify.toml
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: 987d86bf-37d2-4240-a532-c2fc876a1361
        timeout-minutes: 1
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: apps/web
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: notifire
          SENTRY_PROJECT: web
        with:
          environment: prod
          version: v${{ steps.package-version.outputs.current-version }}
          sourcemaps: apps/web/build
